module.exports = {
    SOCIAL: "SOCIALISASI",
    TRANSLATOR: "TRANSLATOR",
    TECH: "TEKNOLOGI",
    WRITER: "PENULIS",
    ADMIN: "ADMINISTRASI",
    DESIGN: "DESAIN",
    RISET: "RISET",
    MANAGEMENT: "MANAJEMEN",
    COACH: "PELATIHAN"
}