-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOLxuEcSBJF+f33hJ
Sbl2ZrGMGjf/Z7sSsXvJLFf0URagCgYIKoZIzj0DAQehRANCAARf2pqfzRLuukMu
G6g/v/Lc5yRVymWpUonggJVwtMsZ2CCGc7KgfiWeJtBBseTz/M9iGaOVjnsYD9tt
enMsjdQi
-----END PRIVATE KEY-----